FUEL_HYDRO = 'Hydro'
FUEL_SOLAR = 'Solar'
FUEL_WIND = 'Wind'
FUEL_GAS_CC = 'Gas-CC'
FUEL_GAS = 'Gas'
FUEL_COAL = 'Coal'
FUEL_BIOMASS = 'Biomass'
FUEL_NUCLEAR = 'Nuclear'
FUEL_TYPE_CLEAN = 'Clean'
FUEL_TYPE_FOSSIL = 'Fossil'
FUEL_TYPE_RENEWABLE = 'Renewable'
FUEL_TYPE_OTHER = 'Other'


FUEL_TYPE_MAPPINGS = {
    FUEL_HYDRO: FUEL_TYPE_RENEWABLE,
    FUEL_SOLAR: FUEL_TYPE_RENEWABLE,
    FUEL_WIND: FUEL_TYPE_RENEWABLE,
    FUEL_BIOMASS: FUEL_TYPE_FOSSIL,
    FUEL_COAL: FUEL_TYPE_FOSSIL,
    FUEL_GAS: FUEL_TYPE_FOSSIL,
    FUEL_GAS_CC: FUEL_TYPE_FOSSIL,
    FUEL_NUCLEAR: FUEL_TYPE_CLEAN,
}
def get_fuel_type(fuel):
    return FUEL_TYPE_MAPPINGS.get(fuel, FUEL_TYPE_OTHER)

LOAD_TYPE_BASE = 'Base'
LOAD_TYPE_PEAKER = 'Peaker'
LOAD_TYPE_OTHER = 'Other'

LOAD_TYPE_MAPPINGS = {
    FUEL_HYDRO: LOAD_TYPE_BASE,
    FUEL_SOLAR: LOAD_TYPE_PEAKER,
    FUEL_WIND: LOAD_TYPE_PEAKER,
    FUEL_BIOMASS: LOAD_TYPE_BASE,
    FUEL_COAL: LOAD_TYPE_BASE,
    FUEL_GAS: LOAD_TYPE_BASE,
    FUEL_GAS_CC: LOAD_TYPE_PEAKER,
    FUEL_NUCLEAR: LOAD_TYPE_BASE,
}
    
def get_load_type(fuel):
    return LOAD_TYPE_MAPPINGS.get(fuel, LOAD_TYPE_OTHER)